---
# Frontend
Frontend.bind_port: "%(FRONTEND_SERVER_PORT|env)"

# Key Management
Server.rsa_key_length: "%(SERVER_RSA_KEY_LENGTH|env)"
PrivateKeys.server_key: "%(%(FRONTEND_PRIVATE_KEY_PATH|env)|file)"
Frontend.certificate: "%(%(FRONTEND_CERT_PATH|env)|file)"
PrivateKeys.executable_signing_private_key: "%(%(FRONTEND_PRIVATE_SIGNING_KEY_PATH|env)|file)"
PrivateKeys.ca_key: "%(%(CA_PRIVATE_KEY_PATH|env)|file)"
CA.certificate: "%(%(CA_CERT_PATH|env)|file)"

# Database
Datastore.implementation: MySQLAdvancedDataStore
Mysql.host: "%(MYSQL_HOST|env)"
Mysql.port: "%(MYSQL_PORT|env)"
Mysql.database_name: "%(MYSQL_DATABASE_NAME|env)"
Mysql.database_username: "%(MYSQL_DATABASE_USERNAME|env)"
Mysql.database_password: "%(MYSQL_DATABASE_PASSWORD|env)"

# We initialize via config file and not grr_config_updater
Server.initialized: True

# Health Checking
Monitoring.http_port: "%(MONITORING_HTTP_PORT|env)"

# Logging
Logging.path: /var/log/grr/
Logging.verbose: True

# Client Packing
Client.name: grr
Client.server_urls: "http://%(CLIENT_PACKING_FRONTEND_HOST|env):%(FRONTEND_SERVER_PORT|env)/"
Client.executable_signing_public_key: "%(%(FRONTEND_PUBLIC_SIGNING_KEY_PATH|env)|file)"
ClientRepacker.output_basename: "%(Client.prefix)%(Client.name)_%(Source.version_string)_%(Client.arch)_%(CLIENT_INSTALLER_FINGERPRINT|env)"

Target:Darwin:
  Config.includes:
    - "/etc/%(Client.name).labels.yaml"

Target:Linux:
  Config.includes:
    - "/etc/%(Client.name).labels.yaml"

Target:Windows:
  Config.includes:
    - "%(Client.install_path)/%(Client.binary_name).labels.yaml"
